- dreambooth_path: models/DreamBooth_LoRA/toonyou_beta6.safetensors
  lora_model_path: ''
  inference_config: configs/inference/inference-v1.yaml
  motion_module: models/Motion_Module/mm_sd_v14.ckpt
  seed:
  - 10788741199826055526
  - 6520604954829636163
  - 6519455744612555650
  - 16372571278361863751
  steps: 25
  guidance_scale: 8
  prompt:
  - In 3d game style, Salvador Dali with a robotic half face
  - unicorn sliding on a rainbow
  - A big Ferris wheel is rotating in an amusement park.
  - With the style of oil painting, a close-up of a bloody mary cocktail
  n_prompt:
  - worst quality, low quality, letterboxed
  W: 512
  H: 512
  L: 16
  random_seed:
  - 10788741199826055526
  - 6520604954829636163
  - 6519455744612555650
  - 16372571278361863751
- dreambooth_path: models/DreamBooth_LoRA/toonyou_beta6.safetensors
  lora_model_path: ''
  inference_config: configs/inference/inference-v1.yaml
  motion_module: models/Motion_Module/mm_sd_v15.ckpt
  seed:
  - 10788741199826055526
  - 6520604954829636163
  - 6519455744612555650
  - 16372571278361863751
  steps: 25
  guidance_scale: 8
  prompt:
  - In 3d game style, Salvador Dali with a robotic half face
  - unicorn sliding on a rainbow
  - A big Ferris wheel is rotating in an amusement park.
  - With the style of oil painting, a close-up of a bloody mary cocktail
  n_prompt:
  - worst quality, low quality, letterboxed
  W: 512
  H: 512
  L: 16
  random_seed:
  - 10788741199826055526
  - 6520604954829636163
  - 6519455744612555650
  - 16372571278361863751
