- dreambooth_path: models/DreamBooth_LoRA/lyriel_v16.safetensors
  lora_model_path: ''
  inference_config: configs/inference/inference-v1.yaml
  motion_module: models/Motion_Module/mm_sd_v14.ckpt
  seed:
  - 10917152860782582783
  - 6399018107401806238
  - 15875751942533906793
  - 6653196880059936551
  steps: 25
  guidance_scale: 8
  prompt:
  - 3 sheep enjoying spaghetti together
  - Two white swans gracefully swam in the serene lake
  - a moose with the style of Hokusai
  - Angelina Jolie's full lips curve into a smile, her gaze intense and captivating.
  n_prompt:
  - 3d, cartoon, lowres, bad anatomy, bad hands, text, error, missing fingers, extra
    digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg
    artifacts, signature, watermark, username, blurry, artist name, young, loli, elf,
    3d, illustration
  - 3d, cartoon, anime, sketches, worst quality, low quality, normal quality, lowres,
    normal quality, monochrome, grayscale, skin spots, acnes, skin blemishes, bad
    anatomy, girl, loli, young, large breasts, red eyes, muscular
  - dof, grayscale, black and white, bw, 3d, cartoon, anime, sketches, worst quality,
    low quality, normal quality, lowres, normal quality, monochrome, grayscale, skin
    spots, acnes, skin blemishes, bad anatomy, girl, loli, young, large breasts, red
    eyes, muscular,badhandsv5-neg, By bad artist -neg 1, monochrome
  - holding an item, cowboy, hat, cartoon, 3d, disfigured, bad art, deformed,extra
    limbs,close up,b&w, wierd colors, blurry, duplicate, morbid, mutilated, [out of
    frame], extra fingers, mutated hands, poorly drawn hands, poorly drawn face, mutation,
    deformed, ugly, blurry, bad anatomy, bad proportions, extra limbs, cloned face,
    disfigured, out of frame, ugly, extra limbs, bad anatomy, gross proportions, malformed
    limbs, missing arms, missing legs, extra arms, extra legs, mutated hands, fused
    fingers, too many fingers, long neck, Photoshop, video game, ugly, tiling, poorly
    drawn hands, poorly drawn feet, poorly drawn face, out of frame, mutation, mutated,
    extra limbs, extra legs, extra arms, disfigured, deformed, cross-eye, body out
    of frame, blurry, bad art, bad anatomy, 3d render
  W: 512
  H: 512
  L: 16
  random_seed:
  - 10917152860782582783
  - 6399018107401806238
  - 15875751942533906793
  - 6653196880059936551
- dreambooth_path: models/DreamBooth_LoRA/lyriel_v16.safetensors
  lora_model_path: ''
  inference_config: configs/inference/inference-v1.yaml
  motion_module: models/Motion_Module/mm_sd_v15.ckpt
  seed:
  - 10917152860782582783
  - 6399018107401806238
  - 15875751942533906793
  - 6653196880059936551
  steps: 25
  guidance_scale: 8
  prompt:
  - 3 sheep enjoying spaghetti together
  - Two white swans gracefully swam in the serene lake
  - a moose with the style of Hokusai
  - Angelina Jolie's full lips curve into a smile, her gaze intense and captivating.
  n_prompt:
  - 3d, cartoon, lowres, bad anatomy, bad hands, text, error, missing fingers, extra
    digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg
    artifacts, signature, watermark, username, blurry, artist name, young, loli, elf,
    3d, illustration
  - 3d, cartoon, anime, sketches, worst quality, low quality, normal quality, lowres,
    normal quality, monochrome, grayscale, skin spots, acnes, skin blemishes, bad
    anatomy, girl, loli, young, large breasts, red eyes, muscular
  - dof, grayscale, black and white, bw, 3d, cartoon, anime, sketches, worst quality,
    low quality, normal quality, lowres, normal quality, monochrome, grayscale, skin
    spots, acnes, skin blemishes, bad anatomy, girl, loli, young, large breasts, red
    eyes, muscular,badhandsv5-neg, By bad artist -neg 1, monochrome
  - holding an item, cowboy, hat, cartoon, 3d, disfigured, bad art, deformed,extra
    limbs,close up,b&w, wierd colors, blurry, duplicate, morbid, mutilated, [out of
    frame], extra fingers, mutated hands, poorly drawn hands, poorly drawn face, mutation,
    deformed, ugly, blurry, bad anatomy, bad proportions, extra limbs, cloned face,
    disfigured, out of frame, ugly, extra limbs, bad anatomy, gross proportions, malformed
    limbs, missing arms, missing legs, extra arms, extra legs, mutated hands, fused
    fingers, too many fingers, long neck, Photoshop, video game, ugly, tiling, poorly
    drawn hands, poorly drawn feet, poorly drawn face, out of frame, mutation, mutated,
    extra limbs, extra legs, extra arms, disfigured, deformed, cross-eye, body out
    of frame, blurry, bad art, bad anatomy, 3d render
  W: 512
  H: 512
  L: 16
  random_seed:
  - 10917152860782582783
  - 6399018107401806238
  - 15875751942533906793
  - 6653196880059936551
