FROM nvidia/cuda:12.2.0-runtime-ubuntu20.04

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        python3.10 \
        python3-dev \
        python3-distutils \
        python3-pip \
        git \
        curl \
        unzip \
        wget \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN apt-get -y install locales && \
    localedef -f UTF-8 -i ja_JP ja_JP.UTF-8

RUN ln -s /usr/bin/python3 /usr/bin/python

RUN pip3 install --no-cache-dir torch==1.13.1+cu117 torchvision==0.14.1+cu117 torchaudio==0.13.1 --extra-index-url https://download.pytorch.org/whl/cu117
RUN pip3 install gdown einops omegaconf safetensors gradio wandb diffusers==0.11.1 transformers=4.25.1 xformers==0.0.16 imageio=2.27.0 decord==0.6.0

RUN AnimateDiff.sh

COPY mm_sd_v14.ckpt $PWD/AnimateDiff/models/Motion_Module/mm_sd_v14.ckpt
COPY mm_sd_v15_v2.ckpt $PWD/AnimateDiff/models/Motion_Module/mm_sd_v15_v2.ckpt

RUN WebVid.sh

COPY image_finetune.yaml $PWD/AnimateDiff/configs/training/image_finetune.yaml

RUN AnimateDiff2.sh


