FROM nvidia/cuda:12.2.0-runtime-ubuntu20.04

RUN ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        python3.10 \
        python3-dev \
        python3-distutils \
        python3-pip \
        git \
        curl \
        unzip \
        libopenmpi-dev \
        libmpich-dev \
        wget &&\
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN pip3 install --no-cache-dir torch==1.13.1+cu117 torchvision==0.14.1+cu117 torchaudio==0.13.1 --extra-index-url https://download.pytorch.org/whl/cu117
RUN pip3 install gdown einops omegaconf safetensors gradio wandb diffusers==0.11.1 transformers==4.25.1 xformers==0.0.16 imageio==2.27.0 decord==0.6.0

RUN git clone https://github.com/m-bain/webvid.git && \
    cd webvid || exit 2 && \
    wget http://www.robots.ox.ac.uk/~maxbain/webvid/results_2M_val.csv && \
    pip3 install mpi4py && \
    python3 download.py --part 0 --csv_path results_2M_val.csv

RUN cd 
RUN cd AnimateDiff || exit 2 && \
    pip3 install accelerate triton && \
    torchrun --nnodes=1 --nproc_per_node=1 train.py --config configs/training/training.yaml && \
    torchrun --nnodes=1 --nproc_per_node=1 train.py --config configs/training/image_finetune.yaml && \
    python3 -m scripts.animate --config configs/prompts/1-ToonYou.yaml && \
    python3 -m scripts.animate --config configs/prompts/2-Lyriel.yaml && \
    python3 -m scripts.animate --config configs/prompts/3-RcnzCartoon.yaml && \
    python3 -m scripts.animate --config configs/prompts/4-MajicMix.yaml && \
    python3 -m scripts.animate --config configs/prompts/5-RealisticVision.yaml && \
    python3 -m scripts.animate --config configs/prompts/6-Tusun.yaml && \
    python3 -m scripts.animate --config configs/prompts/7-FilmVelvia.yaml && \
    python3 -m scripts.animate --config configs/prompts/8-GhibliBackground.yaml
