- dreambooth_path: models/DreamBooth_LoRA/CounterfeitV30_25.safetensors
  lora_model_path: models/DreamBooth_LoRA/lora_Ghibli_n3.safetensors
  lora_alpha: 1.0
  inference_config: configs/inference/inference-v1.yaml
  motion_module: models/Motion_Module/mm_sd_v14.ckpt
  seed:
  - 8775748474469046618
  - 5893874876080607656
  - 11911465742147695752
  - 12437784838692000640
  steps: 25
  guidance_scale: 8
  prompt:
  - Meryl Streep's face shows surprise, her eyes wide and expressive.
  - The Golden Gate Bridge spans the picturesque San Francisco Bay
  - Seven lively puppies play and tumble together.
  - camera pan from left to right, a man wearing sunglasses and business suit
  n_prompt:
  - worst quality, low quality, letterboxed
  W: 512
  H: 512
  L: 16
  random_seed:
  - 8775748474469046618
  - 5893874876080607656
  - 11911465742147695752
  - 12437784838692000640
- dreambooth_path: models/DreamBooth_LoRA/CounterfeitV30_25.safetensors
  lora_model_path: models/DreamBooth_LoRA/lora_Ghibli_n3.safetensors
  lora_alpha: 1.0
  inference_config: configs/inference/inference-v1.yaml
  motion_module: models/Motion_Module/mm_sd_v15.ckpt
  seed:
  - 8775748474469046618
  - 5893874876080607656
  - 11911465742147695752
  - 12437784838692000640
  steps: 25
  guidance_scale: 8
  prompt:
  - Meryl Streep's face shows surprise, her eyes wide and expressive.
  - The Golden Gate Bridge spans the picturesque San Francisco Bay
  - Seven lively puppies play and tumble together.
  - camera pan from left to right, a man wearing sunglasses and business suit
  n_prompt:
  - worst quality, low quality, letterboxed
  W: 512
  H: 512
  L: 16
  random_seed:
  - 8775748474469046618
  - 5893874876080607656
  - 11911465742147695752
  - 12437784838692000640
